[repository]
name = "hyprshot"
authors = ["wilf"]
commit_pins = [
    ["0.54.3", ""]
]

[hyprshot]
description = "Hyprland-only screenshot overlay"
authors = ["wilf"]
output = "build-cmake/libhyprshot.so"
build = [
    "cmake -S . -B build-cmake -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build-cmake --target hyprshot hyprshot-ui"
]
