[repository]
name = "HyprCapture"
authors = ["wilf"]
commit_pins = [
    ["0.54.3", ""]
]

[hyprcapture]
description = "Hyprland-only screenshot overlay"
authors = ["wilf"]
output = "build-hyprpm/libhyprcapture.so"
build = [
    "cmake -S . -B build-hyprpm -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build-hyprpm --target hyprcapture hyprcapture-ui"
]
